name: Build

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [windows-latest] # [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
      #with:
      #  repository: qurious-pixel/smw
      #  ref: devel
    - name: 'Setup x86_64 environment'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: false
        update: true
        install: >-
          base-devel
          git
          wget
          p7zip
          unzip
          libtool
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-toolchain
    - name: 'Build'
      shell: msys2 {0}
      run: |
        make -j4
